---
title: "Sara Lieber's Resume"
author: Sara Lieber
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
  pagedown::chrome_print:
    css: 
      - override.css         # OVERIDE CERTAIN FUNCTIONS OF CSS
      - resume               # DEFAULT FILE
    # set it to true for a self-contained HTML page but it'll take longer to render
    #embed-resources: true
    #standalone: true
    self_contained: true
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print

---

Aside
================================================================================


Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> slieber@uoregon.edu
- <i class="fa fa-github"></i> [github.com/sluopsy](https://github.com/sluopsy)
- <i class="fa fa-linkedin"></i> [linkedin.com/in/sara-lieber-a2811a16b/](https://www.linkedin.com/in/sara-lieber-a2811a16b/)


Skills {#skills}
--------------------------------------------------------------------------------

* <b>Communicating Scientific Ideas</b>
* <b>Developing Psychological Interventions</b>
* <b>Performing Data Analysis in R</b>


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.



Main
================================================================================

Sara Lieber {#title}
--------------------------------------------------------------------------------

I’m a PhD student in the [Social Psychology Program](https://psychology.uoregon.edu/) at the University of Oregon. My research currently focuses on how psychological interventions can be used to promote environmentally-responsible consumer behaviors. I have a passion for teaching statistics to all audiences in a way that is accessible and easy to understand. I am fascinated with the ways that data analysis can help us gain better insights into the world. 


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### PhD, Social Psychology, expected Summer 2023

University of Oregon

Eugene, OR

2016-2023

### MA, Social Psychology

San Francisco State University

San Francisco, CA

2014-2016

### BS, Chemistry

University of North Texas

Denton, TX

2009-2013


Selected Positions {data-icon=laptop}
--------------------------------------------------------------------------------

### Graduate Research Scientist

Advisor: Dr. Gerard Saucier

University of Oregon

2016-2023

- Developed and tested psychological interventions aimed at promoting environmentally-responsible consumption
- Conducted all aspects of the independent research process (e.g., literature review, pre-registration, development of methods and analysis plans, data analysis, and reporting results) 
- Used various statistical analysis tools, incl. descriptive statistics, multiple regression, regression diagnostics, confirmatory & exploratory factor analysis, and unpacking interaction effects 

### Graduate Statistics Instructor

University of Oregon

Eugene, OR

2018-2023

- Taught R language to graduate-level audiences
- Covered topics incl. data cleaning, data visualization, regression analyses & diagnostics, interpreting interactions, bootstrapping, multilevel modeling, network analysis, and more

### Undergraduate Statistics Instructor

San Francisco State University 

San Francisco, CA

2014-2016

- Taught SPSS to undergraduate-level audiences
- Explained statistical concepts in ways that were easy to understand for introductory audiences 
- Covered topics incl. describing data, sampling distributions, hypothesis testing, independent- and paired-samples t-tests, between- and repeated-measures ANOVA, correlations, regression, and more


Teaching Experience {data-icon=chalkboard}
--------------------------------------------------------------------------------

### Graduate Data Analysis (PSY 611/612/613)

* Lab Instructor: Fall 2018, Winter 2019, Winter 2021, Fall 2021, Spring 2022, Winter 2023

University of Oregon


### Statistical Methods (PSY 302)

* Primary Instructor: Summer 2018-2022
* Lab Instructor: Winter 2016, Spring 2019, Spring 2021, Winter 2022

University of Oregon


### Applied Data Analysis (PSY 412/512)

* Lab Instructor: Fall 2017, Fall 2020, Fall 2022

University of Oregon


### Quantitative Reasoning (PSY 171)

* Primary Instructor: Fall 2015, Spring 2016

San Francisco State University


### Psychological Statistics (PSY 371)

* Lab Instructor: Fall 2014

San Francisco State University


Sample Lessons {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Sampling Distributions

Introduced concepts of sampling error, a sampling distribution, and central limit theorem. Taught in Summer 2021 to an undergraduate-level audience. See sample lesson [here](https://github.com/sluopsy/website/raw/main/content/project/sample-lectures/4%20-%20Sampling%2C%20Confidence%20Intervals%20-%20for%20Canvas.pdf).

### One-Way ANOVA

Lesson on how to conduct a between-subjects, one-way ANOVA, including post-hoc test and writing an APA style summary. Taught in Summer 2021 to an undergraduate-level audience. See sample lesson [here](https://github.com/sluopsy/website/raw/main/content/project/sample-lectures/9%20-%20Between-Subjects%20One-Way%20ANOVA%20-%20for%20Canvas.pdf).

### Data Visualization

Basics of data visualization using the `ggplot2` package in `R`. Taught in Fall 2021 to a graduate-level audience. See sample lesson [here](https://uopsych.github.io/psy611_2021/labs/lab-6.html).

University of Oregon

### Regression Diagnostics

How to perform regression diagnostics when using multiple linear regression analyses. Taught in Winter 2021 to a graduate-level audience. See sample lesson [here](https://uopsych.github.io/psy612/labs/lab-6/lab-6.html).

University of Oregon

### Network Analysis

Fundamental concepts related to performing network analyses on community data. Taught in Spring 2022 to a graduate-level audience. See sample lesson [here](https://github.com/sluopsy/website/raw/main/content/project/An%20Introduction%20to%20Network%20Analysis%20-%20Lecture.pdf).

University of Oregon


### Machine Learning

Basics of machine learning analyses, including the concepts of overfitting, training vs testing set, cross-validation, and regression learning methods. Taught in Winter 2023 to a graduate-level audience. See sample lesson [here](https://uopsych.github.io/psy612/labs/lab-10/lab-10.html).

University of Oregon



Selected Presentations {data-icon=file}
--------------------------------------------------------------------------------

### An Analysis of a Social Psychology Approach to Improving Pro-environmental Behaviors

Performed a literature review of currently used social psychology methods for promoting pro-environmental behaviors. Identified areas for potential improvements and suggested future changes that could improve their efficacy. See presentation [here](https://github.com/sluopsy/website/raw/main/content/project/Prelim%20Presentation.pdf).

University of Oregon


### Perspective Taking: Motivation and Impediment to Shared Reality

An analysis of the connection between perspective taking and the concept of shared reality. See paper [here](https://www.sciencedirect.com/science/article/pii/S2352250X1730266X).

University of Oregon


### Unpopular Norms Among Undergraduate Students

An examination of the peculiar phenomenon of unpopular norms among undergraduate students. See presentation [here](https://github.com/sluopsy/website/raw/main/content/project/wpa_unpopular_norms.pdf).

University of Oregon


### Weak Emission-Line Quasars in the Context of a Modified Baldwin Effect

An empirical examination of the properties of weak emission-line quasars, which are high-energy objects that existed in the early universe. See paper [here](https://iopscience.iop.org/article/10.1088/0004-637X/805/2/124).

University of North Texas